### ISSUE TITLE
Permission for Controller not only for Section

### ISSUE THREAD

**Issue by dominixz** [emad-elsaid/Codeigniter-Egypt#3]
I will be great if I can set permission for Class/Method cause I will still coding normally and then i can config who can enter here

**Comment by emad-elsaid** [comment]
you can easily do that by
- extend your controller from Application class instead of CI_Controller
- use $this->print_text() instead of echo
- use perm_check() to check your permissions in the method
- modify the $this->permission member to the permission you want 
- you can make $this->ajax = false to eliminate any automatically generated HTML
